services:
  - type: web
    name: nxt-ai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nxt-ai-db
          property: connectionString

databases:
  - name: nxt-ai-db
    databaseName: nxtai
    user: nxtai_user
    plan: free